version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: 'no'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: 'no'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  phpserver:
    container_name: phpserver_container
    image: php:7.4-apache
    restart: 'no'
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db