version: '3'
services:
  postgres:
    image: postgres:15
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  php:
    image: php:apache
    container_name: my-php-container
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    entrypoint: ["sh", "-c", "a2enmod rewrite && exec apache2-foreground"]

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: 'no'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  postgres_data:
