version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  php:
    image: php:apache
    container_name: my-php-container
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html

volumes:
  postgres_data:
